### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by codynguyen1116** [codynguyen1116/brickimedia-design-guide#1]
Anyone have tips on creating a design framework? I am personally inexperienced with this type of work so if anyone has tips on how to make it as flexible as possible & and how to improve this project that'd be great!

**Comment by MtMNC** [comment]
@codynguyen1116 This is all new for me too I'm afraid. From what I've seen on Codepen it all looks good so far (I don't know whether it reflects the latest version though), but I'd recommend adding a sample HTML page to the repo (or maybe to your github.io) so people can see what it all looks like.

**Comment by georgebarnick** [comment]
+1 for an HTML page, especially one that stays up to date with each commit

**Comment by codynguyen1116** [comment]
Ah yes, that's a good idea. CodePen.io is a nice way to display things but for a project at this big of a scale it's much harder, so I think what I'll do is add a gh-pages branch to this repo. However I will have to look into if whether it's possible to merge files from one branch to another branch since I'm no github expert. :P

**Comment by georgebarnick** [comment]
To avoid making another branch I can just clone it to one of my servers somewhere out of the way and have it updated in some interval (daily? bi-hourly? what interval do you suggest?)

**Comment by codynguyen1116** [comment]
Ah, that'd be very nice! Thanks for providing this, I think every 2 hour sounds good, as long as that's not a strain on your server. Question though, is this clone accessible for us besides you? And if I wanted to customize the site, would I just create some files in this repository?

**Comment by georgebarnick** [comment]
Here you go https://www.georgebarnick.photo/git/brickimedia-design-guide

Just update the files in the repository and they'll be updated on the server within two hours. If you need them updated sooner than that at any point, let me know and I'll manually update it (assuming I get to it before the cron job does)

**Comment by codynguyen1116** [comment]
Thank you!

**Comment by georgebarnick** [comment]
No problem. Let me know if there are any issues or if you need anything further.

**Comment by georgebarnick** [comment]
Updated the crontab that was pulling from git to do so every hour instead of every two hours since it's not that resource intensive and is probably more convenient for you

**Comment by codynguyen1116** [comment]
Ah thank you very much, I appreciate it!

**Comment by codynguyen1116** [comment]
@georgebarnick I have a question, is there a way if the rest of the repo could be imported into the site for the design draft? I've been having trouble trying to figure out how to easily do so so I could show how it'd look.

**Comment by georgebarnick** [comment]
@codynguyen1116 What do you mean? It's all there already

**Comment by codynguyen1116** [comment]
Ah well for example if I were try to use the framework's textfield css will just end up looking like the default input style from the web browser. 
![image](https://cloud.githubusercontent.com/assets/4723983/12009087/a4924f7a-ac2f-11e5-997e-7b3970cb9627.png)

**Comment by georgebarnick** [comment]
You haven't imported all the ```.less``` files have you? That'd be why. I've never used LESS before either so I don't know what it really involves.

**Comment by codynguyen1116** [comment]
Ah I have not, thanks. I'll work on importing them! If I find out a good way to compile all the stylesheets into one instead of multiple for performance I'll use that, but for now this will do.

**Comment by codynguyen1116** [comment]
Gonna close this since it's getting a little long and the problem is solved, so any other problems that come up should be reported as a [new issue](https://github.com/codynguyen1116/brickimedia-design-guide/issues/new).
